pytest-dev/pytest-django

- pytest_django/fixtures.py
This fixes the following error when South tries to access
`management._commands`, which has been dropped in Django 1.7:
…/pytest_django/pytest_django/fixtures.py:41: in _django_db_setup
_handle_south()
…/pytest_django/pytest_django/fixtures.py:128: in _handle_south
patch_for_test_db_setup()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
def patch_for_test_db_setup():
management.get_commands()
if hasattr(settings, "SOUTH_TESTS_MIGRATE") and not settings.SOUTH_TESTS_MIGRATE:
management._commands['syncdb'] = 'django.core'
else:
>           management._commands['syncdb'] = MigrateAndSyncCommand()
E           AttributeError: 'module' object has no attribute '_commands' …
> Skip monkey-patching for South with Django 1.7

- pytest_django/fixtures.py
- tests/test_environment.py
This is a followup to a00a8e4.
> Pass on pytest.config.option.verbose to db setup / flush

- docs/faq.rst
As discussed at Pytest Sprint, alternative approach for https://github.com/pytest-dev/pytest-django/pull/225
> Add faq entry for a manage.py test integration

- pytest_django/plugin.py
This is required in case no (production) database has been created, and
should make the connection blocking more robust altogether.
> Block BaseDatabaseWrapper.ensure_connection instead of CursorWrapper

- docs/faq.rst
> Improve PytestTestRunner code snippet

- pytest_django/plugin.py
This refactors the _parse_django_find_project_ini method into
_get_boolean_value, and uses it for INVALID_TEMPLATE_VARS_ENV, too.
> Add type=bool for django_find_project/INVALID_TEMPLATE_VARS_ENV

- pytest_django/fixtures.py
- pytest_django/live_server_helper.py
- tests/test_fixtures.py
The live server changed a bit in Django 1.11 (current Django master). This PR updates pytest-django to deal with it.
> Django 1.11 live server updates

- README.rst
I visit PyPI pages when upgrading packages to try find the projects' changelogs. This would help with such hunting, making it more obvious :)
> README - link to changelog

- docs/changelog.rst
- docs/helpers.rst
- pytest_django/plugin.py
- tests/test_environment.py
> added autouse function scoped fixture that cleares django.contrib.sites.models.SITE_CACHE

- tox.ini
- removed duplicate section
- ordered elements alphabetically to prevent future problems
@pelme this fixes #428
> removed duplicate command definitions

- README.rst
just to quickly see latest version on pypi
> added pypi badge go README.md

- docs/faq.rst
- docs/index.rst
- docs/tutorial.rst
- Add test discovery config instruction to tutorial chapter
- Use code-block directive for code blocks
Addresses issue #67.
> [Docs] Add test discovery config instruction to tutorial chapter

- .travis.yml
- tox.ini
> CI version updates

- docs/helpers.rst
> doc: fix case/grammar with mailoutbox

- setup.py
Fixes https://github.com/pytest-dev/pytest-django/issues/465.
> setup.py: unpin setuptools_scm

- README.rst
- docs/database.rst
- docs/faq.rst
- docs/helpers.rst
- docs/index.rst
- docs/tutorial.rst
- docs/usage.rst
Fix broken links of pytest documentation.
> Fix broken links

- docs/helpers.rst
> Example for usage of rf, admin_user and class-based views

- .travis.yml
- tests/test_django_settings_module.py
- tests/test_urls.py
- tox.ini
Includes https://github.com/pytest-dev/pytest-django/pull/526.
> Support Django 2.0

- docs/helpers.rst
> .create => .create_user

- setup.py
pypa/warehouse#4090 has been merged
> Add Django 2.1 classifier

- tox.ini
Fixes https://github.com/pytest-dev/pytest-django/issues/567.
> tox.ini: fix checkqa in envlist

- tests/test_environment.py
Ref: https://github.com/django/django/commit/65503ca09798bffbe8226c3a8a7953906042b2ee
> Fix tests for Django master (2.2)

- pytest_django/plugin.py
See https://github.com/pytest-dev/pytest-django/issues/641
> Avoid OSError during django path detection

- pytest_django/fixtures.py
Closes https://github.com/pytest-dev/pytest-django/issues/661.
> _assert_num_queries: make code clearer

- pytest_django/plugin.py
- tests/test_manage_py_scan.py
Ref: https://github.com/pytest-dev/pytest-django/issues/689
> django_find_project: add cwd as fallback always

- .travis.yml
- pytest_django/plugin.py
- setup.py
- tests/test_unittest.py
- tox.ini
Fixes https://github.com/pytest-dev/pytest-django/issues/698.
> Fix/skip disabling/handling of unittest methods with pytest 4.2+

- .travis.yml
- setup.py
- tests/test_db_setup.py
- tox.ini
Ref: https://github.com/pytest-dev/pytest-django/issues/688
> tests: skip tests without xdist

- tests/test_environment.py
Via https://github.com/pytest-dev/pytest-django/issues/685#issuecomment-460436835.
> Test default_if_none template filter with dict keys

- .travis.yml
Via https://github.com/pytest-dev/pytest/pull/5211.
> ci: Travis: use newer PyPy

- .travis.yml
After more than half a year this still triggers timeouts on their end...
> ci: remove codecov flags

- .travis.yml
- tests/test_db_setup.py
Ref: https://github.com/pytest-dev/pytest-django/issues/712#issuecomment-497440920
> tests: follow-up fix for test_sqlite_database_renamed

- pytest_django/plugin.py
- tests/test_unittest.py
Fixes https://github.com/pytest-dev/pytest-django/issues/772.
Ref: https://github.com/pytest-dev/pytest/pull/5996
> Monkeypatch pytest instead of Django to workaround pytest bug

- pytest_django/plugin.py
- tests/test_django_configurations.py
- tests/test_django_settings_module.py
Closes https://github.com/pytest-dev/pytest-django/issues/790
> Report django-configurations setting

- setup.py
> Add a link from PyPI to the source code

- docs/database.rst
> Remove Django version from --nomigrations heading

- .travis.yml
- tox.ini
Pulled out of https://github.com/pytest-dev/pytest-django/pull/825.
> ci: tox/travis: pytest53

- docs/changelog.rst
- docs/conf.py
- docs/configuring_django.rst
- docs/contributing.rst
- docs/database.rst
- docs/faq.rst
- docs/helpers.rst
- docs/index.rst
- docs/tutorial.rst
- docs/usage.rst
- pytest_django/fixtures.py
> docs: some fixes/cleanups

- .github/workflows/main.yml
- setup.cfg
- tox.ini
Django 3.2 is due to be released on April 6th.
> Run tests against Django 3.2

- docs/database.rst
Updated argument `--nomigrations` to `--no-migrations` in documentation according to `pytest --help`.
> Updated documentation --nomigrations to --no-migrations

- docs/helpers.rst
I know this is a tiny change and and maybe not worth a PR, but my OCD kicked in and forced me to raise this PR.
Also, after using pytest-django more and more I hope that this might be the first but not last PR and I wanted to get started somewhere.
Happy to receive feedback.
> add some special characters to fix rendering of docs

- README.rst
- Manage test dependencies with pytest fixtures. ~~<https://pytest.org/en/latest/fixture.html\>\~\~_
- Manage test dependencies with pytest fixtures. <https://pytest.org/en/latest/how-to/fixtures.html\>_
- Make use of other pytest plugins <https://pytest.org/en/latest/how-to/plugins.html\>.
| Test | Result |
| ----------- | :-----------: |
| tests/test_asserts.py  |[0%] |
| tests/test_database.py  | [5%] |
| tests/test_environment.py  |    [10%] |
| tests/test_fixtures.py  |  [17%] |
| tests/test_unittest.py  | [21%] |
| tests/test_database.py  | [24%] |
| tests/test_fixtures.py  | [26%] |
| tests/test_asserts.py   | [26%] |
| tests/test_database.py  |[ 39%] |
| tests/test_db_access_in_repr.py  | [40%] |
| tests/test_db_setup.py  | [47%] |
| tests/test_django_configurations.py  | [49%] | …
> docs(readme): update readme broken-links.

- pytest_django/fixtures.py
This is more flexible/orthogonal.
> Always use a TestCase subclass

- docs/changelog.rst
- docs/helpers.rst
- pytest_django/fixtures.py
- pytest_django/plugin.py
- tests/test_database.py
- tests/test_db_setup.py
Thanks to Aymeric Augustin, Daniel Hahler and Fábio C. Barrionuevo da
Luz for previous work on this feature.
Fix #329.
Closes #353.
Closes #721.
Closes #919.
Closes #956.
Closes #970.
> Add support for rollback emulation/serialized rollback

- docs/changelog.rst
- pytest_django/fixtures.py
- tests/test_database.py
- tox.ini
> Make `pytest.mark.django_db(reset_sequences=True)` imply `transaction=True` again

- docs/managing_python_path.rst
> fix a typo

- docs/conf.py
- pytest_django/fixtures.py
- pytest_django/live_server_helper.py
- pytest_django/plugin.py
- pytest_django_test/app/views.py
- pytest_django_test/db_helpers.py
- tests/test_django_settings_module.py
- tests/test_environment.py
- tests/test_fixtures.py
> Update old string formatting to f-strings

- .github/workflows/main.yml
- README.rst
- docs/changelog.rst
- docs/configuring_django.rst
- docs/index.rst
- docs/tutorial.rst
- pytest_django/asserts.py
- setup.cfg
- tox.ini
This PR add setting examples using pyproject.toml file in the documentation
> Add setting example using pyproject.toml file.

- pytest_django/plugin.py
- tests/test_unittest.py
Should have done this in #1081
> Checks for tags on any `SimpleTestCase` not just `TransactionTestCase`

- .github/workflows/main.yml
https://github.com/actions/setup-python/releases
> Upgrade GitHub Action setup-python

- .github/workflows/main.yml
> ci: try to fix coverage upload

- .github/dependabot.yml
Ref: https://github.com/pytest-dev/pytest-django/pull/1103#issuecomment-1880164519
> Configure dependabot to check for updates to GitHub Actions every weekday

- .github/workflows/main.yml
I'm afraid that PR https://github.com/pytest-dev/pytest-django/pull/1203 will take some time to get accepted, moving changes outside that have little risk.
> Simplify tox environment

- .github/workflows/main.yml
> Update tox version

- pyproject.toml
- tox.ini
Reverts pytest-dev/pytest-django#1227
> Revert "Modernize pyproject + tox"

- .editorconfig-checker.json
Related to https://github.com/pytest-dev/pytest-django/pull/1225, https://github.com/pytest-dev/pytest-django/pull/1226, #1228
> Fix more local ec issues
