pytest-dev/pytest-django

- docs/database.rst
- pytest_django/fixtures.py
- pytest_django/migrations.py
- pytest_django/plugin.py
- tests/test_db_setup.py
When there are several migrations to run, the database setup can be very slow. This pull request uses [a hack](https://gist.github.com/NotSqrt/5f3c76cd15e40ef62d09) to disable Django 1.7 migrations when the option `--nomigrations` is given.
It should not be a problem when you use `--reuse-db` in your workflow, but the `--nomigrations` flag should help who needs / prefers to create the database on every run.
It seems that [until Django 1.9](https://groups.google.com/forum/#!topic/django-developers/PWPj3etj3-U) is safe to use this hack -- I hope we have another way to do it then. 
There's also a [plugin for manage.py](https://github.com/henriquebastos/django-test-without-migrations) to do it.
My tests took 120 seconds before and are taking just 10 seconds now, so I hope it gets merged.
> Create --nomigrations option to disable Django 1.7 migrations

- setup.cfg
This skips less tests by default.
> setup.cfg: use settings_sqlite_file for DSM

- tests/test_unittest.py
Not sure how useful this really is, but it ensures that the methods are
being called actually.
> Add TestUnittestMethods

- pytest_django/fixtures.py
- tests/test_fixtures.py
This also removes a test marked as `xfail`, which is not supposed to fail as far as I understand.
@pelme 
Can you confirm that the test should not have been expected to fail in the first place?
> Cleanup interaction with `live_server` and `transactional_db`

- .travis.yml
- generate_configurations.py
`sudo: false` makes sense (to enable a container based environment, which is faster and has more features).
But I don't now if we want to allow failure of Django master?
Another interesting option (when we'll use the allowed failures) is `fast_finish`: http://docs.travis-ci.com/user/build-configuration/#Fast-finishing
> Travis improvements

- setup.py
I don't know if PyPI has a convention for naming these, but that's
what the Open Source Initiative calls this one [1].  However, the text
is a bit different from the official upstream version which has:
3. Neither the name of the copyright holder nor the names of its
contributors may be used...
instead of the local:
* The names of its contributors may not be used...
There's also an "COPYRIGHT HOLDER" -> "COPYRIGHT OWNER" change in the
local disclaimer.
It would be nice if we could stick to the standard upstream phrasing.
[1]: http://opensource.org/licenses/BSD-3-Clause
> setup.py: Mention the 3-clause BSD license in our metadata

- docs/faq.rst
- tests/conftest.py
- tests/test_db_setup.py
I've investigated into issue #158, and recognized that the South tests were not proper.
This is meant to fix these and adds a test that should trigger #158, but does not (yet).
> Fix south tests

- pytest_django/lazy_django.py
- tests/test_django_settings_module.py
> Test and fix for issue #146

- pytest_django/fixtures.py
It doesn't look like the `db` fixture docstring makes much sense. First it says it will setup the DB without transaction support and then it says it will roll back changes at the end of the transaction. My understanding is there are no transactions and therefore the second sentence of the existing docstring must go away.
> db fixture: fixed docstring

- .travis.yml
- generate_configurations.py
- tox.ini
> Travis: test all Django versions against Python 2 and 3

- requirements.txt
isort is not really required for the project. And it actually caused
some weird problem, because of its dependency on pies, where pies==2.6.5
installed pies2overrides for Python 3.
This reverts commit 0cc993549ee585c59f2783d171d1d3074f7d60db.
@pelme 
Any objections (you've added it)?
> Revert "Added isort to requirements"

- pytest_django_test/db_helpers.py
This removes the dependency on the 'sqlite3' third-party program, which is not present by default on most distributions (eg: Ubuntu 14.04) in favor of the sqlite3 library built into Python.
Fixes https://github.com/pytest-dev/pytest-django/issues/244
> Use builtin sqlite3 library instead of 'sqlite3' CLI

- docs/helpers.rst
- docs/usage.rst
- pytest_django/plugin.py
- tests/test_environment.py
Django catches all `VariableDoesNotExist` exceptions to replace
them in templates with a modifiable string that you can define in
your settings.
Sadly that doesn't allow you to find them in unit tests.
`_fail_for_invalid_template_variable` sets the setting
`TEMPLATE_STRING_IF_INVALID` to a custom class that not only fails
the current test but prints a pretty message including the template
name.
A new marker allows disabling this behavior, eg:
@pytest.mark.ignore_template_errors
def test_something():
pass
This marker sets the setting to None, if you want it to be a string,
you can use the `settings` fixture to set it to your desired value.
> Adds tests for invalid template variables

- pytest_django/plugin.py
- tests/test_manage_py_scan.py
With `pytest --version` and `pytest --help` pytest-django should not
throw an error (ImportError) in case of invalid DSM settings etc.
This removes hooking into `pytest_configure` altogether, and moves the
late call do `_setup_django` into the session-scoped autoload fixture instead.
Fixes https://github.com/pytest-dev/pytest-django/issues/235
> Skip Django setup and manage.py scanning with "pytest --help"

- docs/changelog.rst
- docs/configuring_django.rst
- pytest_django/plugin.py
- tests/test_django_settings_module.py
> Added a new option  to avoid forcing of DEBUG setting to False

- docs/changelog.rst
- docs/configuring_django.rst
> doc: mention `addopts` to set `--ds`; typos

- MANIFEST.in
Inlcude test for downstream testing, resolves #290
Signed-off-by: Justin Lecher <jlec@gentoo.org>
> Include tests in pypyi tarball

- pytest_django/db_reuse.py
- pytest_django/fixtures.py
- tests/test_environment.py
Django 1.8 supports `--keepdb` [1], and it makes sense to make use of
it.  This should probably handle migrations in the context of
`transactional_db` better, i.e. by re-applying migrations with a flushed
DB.
1: https://docs.djangoproject.com/en/1.8/ref/django-admin/#django-admin-option---keepdb
> Use Django's `--keepdb` with Django 1.8+

- .travis.yml
- generate_configurations.py
- tox.ini
Python 3.2 is not supported by pip 8+ anymore, which is used by tox via
Python 3.5's `virtualenv_support`.
Failing build: https://travis-ci.org/pytest-dev/pytest-django/jobs/106463859.
> tests: update versions, drop support for Python 3.2

- pytest_django/plugin.py
The `--reuse-db` option's help still mentions the `--no-db` option even though it was removed: https://github.com/pytest-dev/pytest-django/commit/bb7213bba53352fe56e563462deeaec92fbf2461#diff-87c0c2cb9262dd6c4384e140e51d8e64L69
> Remove reference to --no-db in command-line help

- README.rst
- docs/managing_python_path.rst
- setup.cfg
- setup.py
As per their email ‘Changes to project subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.
> Convert readthedocs link for their .org -> .io migration for hosted projects

- docs/changelog.rst
- docs/database.rst
- pytest_django/plugin.py
- tests/test_db_setup.py
This also adds `--no-migrations` as an alias.
Fixes https://github.com/pytest-dev/pytest-django/issues/311.
> Add `--migrations` option to negate `--nomigrations`

- pytest_django/fixtures.py
Just spotted this. It doesn't fail because functions can be compared with types fine on Python 2, and no one is using Django < 1.5 on Python 3. Still worth fixing.
> Fix get_django_version() asserts for django_user_model / django_username_field

- generate_configurations.py
- setup.py
- tox.ini
This is only required with Django versions before 1.7, and is meant to
make the diff of config updates simpler.
> generate_configurations: remove UID / db creation from tox configs

- pytest_django_test/db_helpers.py
- tests/test_database.py
- tests/test_fixtures.py
It is not needed anymore with newer Django versions.
> Remove the noop_transactions() helper.

- pytest_django/plugin.py
- tests/test_database.py
This should fix various places where the production database could accidentally been accessed.
/cc @blueyed
> Block Django database access as early as possible.

- pytest_django/compat.py
- pytest_django/fixtures.py
This removes the ugly workaround of instantiating DiscoverRunner.
This fixes #376.
> Use django.test.utils.{setup_databases,teardown_databases}

- docs/database.rst
- pytest_django/compat.py
- pytest_django/fixtures.py
- pytest_django/plugin.py
- tests/test_fixtures.py
> Improve django_db_blocker

- docs/changelog.rst
Markdown code highlighting uses one tick but RST uses two, I suspect these were just a mixup from that confusion.
> Changelog - fix some code highlighting

- pytest_django/compat.py
- pytest_django/fixtures.py
- pytest_django/plugin.py
- pytest_django/pytest_compat.py
- tests/test_database.py
- Use getfixturevalue instead of getfuncargvalue if it exists
> Avoid deprecation warnings on pytest 3.0

- pytest_django/plugin.py
The _django_clear_outbox fixture creates a new list, not clearing the existing mailbox. This can cause problems as fixture execution order cannot be guaranteed, and there might be fixtures (in my case an mailoutbox fixture) that just contains a reference to mail.outbox to be able to check what emails was sent out by the system... however, tests fails randomly as sometimes my own fixture actually gets reference to an old mailbox, not the newly created one...
> _django_clear_outbox should clear mail.outbox instead of creating new list

- pytest_django/fixtures.py
- tests/test_fixtures.py
When changing/deleting a setting, the
django.test.signals.setting_changed fixture will be sent, just like
Django's override_settings decorator.
Refs #93, #46.
more and more apps are using this signal to clean their caches, so more and more settings can't be changed with this fixture
> Fixed #136 - fix the settings fixture for certain settings.

- docs/changelog.rst
- docs/helpers.rst
- pytest_django/plugin.py
- tests/test_environment.py
- tests/test_fixtures.py
pytest-django doesn't provide any mechanism to get the mail outbox, however it is clearing the mailbox, that effects external fixtures that might want to interact with the mail.outbox. This fixture stores previous outbox (if any), creates a new list for usage in fixture, and then restores the state to what it was previously...
This PR is initiated to add a mailoutbox fixture, and if interested of getting this released, I would enhance it with documentation and possible tests...
PR #407 would not be needed if this is chosen as the path to go...
> Adding mailoutbox fixture, and removing internal _django_clear_outbox

- pytest_django/migrations.py
> in django >= 1.9 one can set module value to None in settings.MIGRATION_MODULES to not run

- pytest_django/plugin.py
- tests/test_environment.py
Refs #410.
@peterlauri please have a look!
> Make sure mail.outbox == foo and mail.outbox != bar raises exceptions.

- pytest_django/plugin.py
- tests/test_unittest.py
Here's a failing test for #405, tests on travis-ci and tox pass. This helped to isolate it to occurring on latest `pytest==3.0.3`, probably has something to do with the `pdb` changes in the last minor releases. Specifically, [changelog for 3.0.2](https://github.com/pytest-dev/pytest/blob/master/CHANGELOG.rst#302) includes merge of PR pytest-dev/pytest#1890:
> Do not call tearDown and cleanups when running tests from unittest.TestCase subclasses with --pdb enabled. This allows proper post mortem debugging for all applications which have significant logic in their tearDown machinery (#1890). Thanks @mbyt for the PR.
In essence, it's not a bad change; but, when combined with `--reuse-db` or when `setUp` create unique Django objects this fails hard.
I guess one way, would be to re-enable this …
> Add a failing unittest case when using `--pdb` option

- docs/changelog.rst
- docs/helpers.rst
- pytest_django/plugin.py
- tests/test_environment.py
> re-introduced auto clearing of mail.outbox

- docs/_templates/sidebarintro.html
- docs/changelog.rst
- docs/conf.py
The current docs use the default theme, which is a bit old-fashioned. This PR makes our docs use the same Sphinx theme [as the pytest project](https://github.com/pytest-dev/pytest/blob/master/doc/en/conf.py#L108-L113).
- Use Flask theme** for docs (same as pytest project)
- Use anonymous links in changelog to avoid link name clashes
** Flask is an [Alabaster theme](https://alabaster.readthedocs.io/en/latest/) clone.
Note
-----
- The Flask theme **requires** installing [Flask-Sphinx-Themes](https://github.com/pallets/flask-sphinx-themes) via `pip install Flask-Sphinx-Themes` (I've found no place for that in the `Makefile` or `../requirements.txt`) -- _should be added!_
- `pygments_style` is overridden [despite related instruction](https://github.com/pallets/flask-sphinx-themes#pygments-styl …
> Pimp up the docs! (use same theme as pytest)

- .travis.yml
Fixes https://github.com/pytest-dev/pytest-django/issues/448.
> Travis: move pypy3 jobs to allow_failures for now

- requirements.txt
- Add Flask-Sphinx-Themes to requirements for building the docs
Fixes #449.
Side Note
----------
I feel it's a bit odd to have a `requirements.txt` file in the root folder, which is - kind of - "pulled in by magic" (or by convention) by ReadTheDocs.
Isn't `requirements.txt`, when it exists in a package project's root folder, either referenced by `setup.py` for installation or expected to be used manually for installation of the package or project?
It's not all straight-forward. Also, now we have a dependency for building _the docs_ in the root folder's requirements file. Odd. I think we should fix that.
> Fix building the docs on RTD

- docs/index.rst
The current docs contain the essential in the introduction paragraph, but they're a bit hard to read. Let's make it super-easy, legible and beautiful to help reduce the drop-off rate for newcomers!
- Make Quick Start section easier to read for developers
- Move table of contents down, promote the "Why use it?" section
- Use Title Case (almost) uniformly
> [Docs] Make Quick Start section easier to read

- pytest_django/plugin.py
- tests/test_environment.py
This will be there with Django 1.9+ always, and in case of
`settings.TEMPLATE_DEBUG` before.  It also not go up to the Template,
but uses the nearest location (which is required with extending
templates).
Using `django.template.base.Origin` also gives the benefit of having the
full/absolute path.
btw: I suggested to not throw it with the `default` filter in Django in https://github.com/django/django/pull/8200 - we might add it in pytest-django already / instead (if it gets not accepted in Django).
> Improve --fail-on-template-vars: use origin if available

- pytest_django/plugin.py
As per https://www.quantifiedcode.com/app/project/ffc21345b6884ba6bf92a1c95f9362fd/diff/d4f42eae622dea861fa6e628b9f52da6026c43b3/af04673a2ba97d6244489edac946cc1bc29a0533/issues?groups=code_patterns%3A7I7lGdCx%3Af0,code_patterns%3Akv4o9Hx2%3Af0.
> Make InvalidVarException._get_origin a staticmethod

- .gitignore
- Makefile
In the end it should use tox probably from there, but it helped to discover https://github.com/pytest-dev/pytest-django/issues/483 in its current state.
> Makefile: use virtualenv in build/venv

- tests/test_django_configurations.py
- tox.ini
It was pinned to 1.0 before, and should cause test failures now.
Ref: https://github.com/pytest-dev/pytest-django/issues/483
> Use django-configurations==2.0 in tests

- .coveragerc
- .travis.yml
- tox.ini
Can be viewed here: https://codecov.io/gh/pytest-dev/pytest-django/tree/coverage
> Travis: add coverage reporting via pytest-cov on codecov.io

- tests/test_environment.py
This shows issue https://github.com/pytest-dev/pytest/issues/580, which
is fixed in pytest 3.2.1.
> tests: test_invalid_template_variable: use include

- .travis.yml
- README.rst
- docs/contributing.rst
- docs/helpers.rst
- docs/managing_python_path.rst
- pytest_django/compat.py
- pytest_django/fixtures.py
- pytest_django/plugin.py
- tests/test_db_setup.py
- tests/test_environment.py
- tests/test_fixtures.py
- tox.ini
As suggested in https://github.com/pytest-dev/pytest-django/pull/521#discussion_r143324799
> Drop support for Django 1.7

- .coveragerc
This makes it easier for Codecov to parse it.
> .coveragerc: use a single source, but includes

- tests/conftest.py
Ref: https://github.com/pytest-dev/pytest-django/pull/412#issuecomment-340129160
> tests: unset PYTEST_ADDOPTS with inner pytest runs

- .travis.yml
The current builds are very slow (~30mins for pypy3).
Try newer/current versions.
Slowness comes from running with coverage, so I will likely only skip this, but use the versions provided by Travis by default.
> Travis: skip coverage reporting with pypy/pypy3

- docs/database.rst
Fix typo in the section: Populate the database with initial test data.
> doc: fix typo

- tests/test_environment.py
- tests/test_unittest.py
- tox.ini
Fixes https://github.com/pytest-dev/pytest-django/issues/550.
> Fix tests for pytest 3.3

- pytest_django/fixtures.py
- pytest_django/live_server_helper.py
- tests/test_fixtures.py
As the possibility to define a fixed live server port has been added back in Django 1.11.2 (https://code.djangoproject.com/ticket/28212), I'd like to have it available in pytest-django as well.
> Allow setting the live server port.

- docs/helpers.rst
- Includes misc documentation cleanup
- Resolves #553
> Document use of authenticated `client` and `django_user_model`

- .travis.yml
Re-using an existing `.tox` dir will result in less informative error
messages, e.g. when `python_requires` is broken [1].
1: https://travis-ci.org/pytest-dev/pytest-django/jobs/310792370
> Travis: do not cache tox dirs

- .coveragerc
- .travis.yml
Fixes the following warning:
> Coverage.py warning: --include is ignored because --source is set
> (include-ignored)
Ref: https://bitbucket.org/ned/coveragepy/issues/621/include-ignored-warning-when-using
> .coveragerc: move include to report section

- .travis.yml
- tox.ini
See https://github.com/pytest-dev/pytest-django/issues/473#issuecomment-353352328
This adds a Travis build stage to automatically release to PyPI when a new tag is pushed.
To finish this up, the encrypted PyPI password will need to be added to `.travis.yml` attn @blueyed 
```
gem install travis
travis encrypt
```
Copy the output into `.travis.yml`
```yaml
provider: pypi
user: blueyed
password:
secure: '... encrypted password from `travis encrypt` ...'
```
> Automatically release to PyPI with Travis

- pytest_django/live_server_helper.py
This can be done now since support for Django 1.7 has been dropped.
> live_server: use self.thread.terminate() directly

- docs/conf.py
This is required to resolve e.g. `str` as a type.
> docs: add intersphinx

- docs/changelog.rst
- docs/conf.py
- docs/helpers.rst
- pytest_django/plugin.py
- tests/test_fixtures.py
DNS lookups can be really slow, and it is good to skip them in general,
and have a more stable header in the mails.
TODO:
> Patch DNS_NAME used in mail module by default

- .travis.yml
- README.rst
- setup.py
Travis does not support 3.7 on the Trusty images: https://docs.travis-ci.com/user/languages/python/#development-releases-support.. :/
> Support Python 3.7

- docs/helpers.rst
- pytest_django/fixtures.py
- pytest_django/plugin.py
- tests/test_fixtures.py
Often I don't want to test against the exact number of queries performed by a particular piece of code but just be sure that changes to the codebase don't end up in an unnoticed excessive increase of queries.
[django-test-plus](https://github.com/revsys/django-test-plus#assertnumquerieslessthannumber---context) has a really nice helper for this kind of scenario: https://github.com/revsys/django-test-plus#assertnumquerieslessthannumber---context
This PR tries to port the same functionality to `pytest-django`.
Open issues:
* No tests so far
* Does renaming `assert_num_queries` to `assert_exact_num_queries` make sense?
Cheers,
Andreas
> Add fixture for asserting maximum number of database queries

- docs/helpers.rst
- pytest_django/fixtures.py
- pytest_django/plugin.py
- tests/test_database.py
Picking up work done in #308
This adds support for using the reset_sequences feature of Django's TransactionTestCase.
It will try to reset all automatic increment values before test execution, if the database supports it. This is useful when you have tests that rely on such values, like ids or other primary keys such as snapshot testing of apis with [snapshottest](https://github.com/syrusakbary/snapshottest).
> Support reset sequences

- docs/index.rst
Django can do this too with `--keepdb` since 1.8 so it seems unfair to list this as an advantage.
> Remove 'database reuse' as an advantage

- pytest_django/plugin.py
- setup.py
- tests/conftest.py
The dependency on `pathlib` was added in #631. A backport is needed for Python <3.4.
The `pathlib` package [on PyPI](https://pypi.org/project/pathlib/) is maintenance-only and comes with a message about using `pathlib2` for an up-to-date version. Also `pytest` itself uses `pathlib2` so currently I'm getting both packages installed when one would do.
This change in `setup.py` seems to be all that's needed to switch.
> Use pathlib2

- pytest_django/plugin.py
- tests/test_manage_py_scan.py
Fixes https://github.com/pytest-dev/pytest-django/issues/637
> Fix sys.path.insert for project path: insert absolute path

- docs/configuring_django.rst
Tidy wording and improve syntax highlighting - single backticks had been used in some places instead of double, giving italics rather than code highlighting.
> Improve 'configuring' docs

- .travis.yml
Debugging dropped coverage: https://codecov.io/gh/pytest-dev/pytest-django/tree/efc08dc83d79be801725a494821b2f0c0bb50fad
(reported OK in the build, but not on codecov)
> Travis: pin pytest-cov==2.5.1

- pytest_django/plugin.py
- tests/test_manage_py_scan.py
> Avoid crash after OSError during django path detection

- setup.cfg
Signed-off-by: Philippe Ombredanne <pombredanne@nexb.com>
> Ensure that the LICENSE file is included in wheels

- docs/database.rst
I stumbled upon this snippet in docs but I'm using Postgres, so `executescript` is not available in `psycopg`, I quickly found that it was supposed to be `execute` only, however, I still think it's valuable to have this warning for whoever comes across this.
Took the time to also fix a few minor typos.
> docs: add warning about sqlite specific snippet + fix typos

- pytest_django/lazy_django.py
- tests/test_django_settings_module.py
Some modules, e.g. hypothesis, load some Django modules for their own fixtures.
This means that the `django.conf` module sometimes gets loaded, even though it's
never used (and the settings are not initialized).
This causes unrelated test failures when pytest_django is installed, as
pytest_django considers that having a loaded django.conf means the settings are
set up and ready to be modified. The Django settings object provides a flag to
check this condition, which we now use.
Add a regression test that mimics what hypothesis did which makes pytest-django
fail.
Closes #599.
> Refine the django.conf module check to see if the settings really are configured

- pytest_django/fixtures.py
- tests/test_fixtures.py
Email could be a username field. If this is the case, we shouldn't add it into kwargs, because that would cause the same argument to be passed twice. I didn't create test case for that because this would require setting up custom user model and injecting it into a test case. Maybe there is an easier way I didn't see?
> Don't add email to extra arguments

- pytest_django/fixtures.py
Will be deprecated in pytest 4.1.
Ref: https://github.com/pytest-dev/pytest/commit/b88c3f8f828
> Use request.config instead of pytest.config

- setup.py
Ref: https://github.com/pytest-dev/pytest/issues/4704
> install_requires: do not allow pytest 4.2.0

- pytest_django/fixtures.py
- tests/test_db_setup.py
For Django configurations using multiple databases, there's a subtle bug
that doesn't rename databases, if there's an SQLite one that triggers
the `return` statement in the existing feature.
As the return value doesn't seem to be used, we can just move to the
next iteration in the `for`-loop, and evaluate the following DB.
A test was added to consider this scenario.
> Fix DB renaming fixture for Multi-DB environment

- pytest_django/plugin.py
- tests/test_db_setup.py
> Ordering of tests

- docs/conf.py
Sphinx 2.0 dropped support for it.
See pytest-dev/pytest#4922
> Remove deprecated Sphinx directive add_description_unit()

- pytest_django/fixtures.py
Previously it would cause pytest to crash, and this is just something to
warn about anyway.
Ref: https://github.com/django/channels/issues/1091#issuecomment-489389450
> django_db_setup: warn instead of crash with teardown errors

- pytest_django/fixtures.py
- tests/test_db_setup.py
It would still add some overhead (especially with regard to output
noise).
> Mock out migrate.Command with `--no-migrations`

- tests/conftest.py
This is required for when conftests are loaded before Django gets setup
(i.e. when it would be done in pytest_configure only).  Not necessary,
but easier to improve things from there.
Taken out of #719.
> tests/conftest.py: move import of db_helpers

- .travis.yml
- tests/test_db_setup.py
- tox.ini
Ref: https://github.com/django/django/blob/1.11.20/django/db/backends/sqlite3/creation.py#L19
Fixes https://github.com/pytest-dev/pytest-django/issues/712.
> tests: fix test_sqlite_database_renamed for Django 1.11

- pytest_django/plugin.py
While looking into https://github.com/pytest-dev/pytest-django/issues/710.
> Revisit unittest handling

- pytest_django/fixtures.py
- pytest_django/plugin.py
The following is preventing compatibility with the newly release pytest 5.0:
```python
pytest.PytestDeprecationWarning: The `funcargnames` attribute was an alias for `fixturenames`, since pytest 2.3 - use the newer attribute instead.
```
> Fix compat with pytest 5.x

- .gitignore
- docs/database.rst
- pytest_django/fixtures.py
- pytest_django/plugin.py
- tests/test_db_setup.py
When tests are executed using Tox in parallel, modify the test database
names, to avoid name collisions between processes.
This change renames the existing
`django_db_modify_db_settings_xdist_suffix` fixture, to a generic
`django_db_modify_db_settings_parallel_suffix` one, in case more
scenarios/tools have to be considered in the future.
It also handles projects where both `pytest-xdist` and parallel `tox`
are being using, generating database names like
`test_default_py37-django21_gw0`.
This change is based on `tox` new parallel mode [0].
Resolves #678.
[0] https://github.com/tox-dev/tox/pull/1102
> Rename test databases when running parallel Tox

- pytest_django/plugin.py
- tests/test_unittest.py
Fixes https://github.com/pytest-dev/pytest-django/issues/769.
> Django unittests: restore "debug" function

- pytest_django/plugin.py
Ref: https://github.com/django/django/pull/7436
Ref: https://github.com/pytest-dev/pytest-django/issues/769
> Django TestCase: skip patching `debug()` for Django 3.1

- pytest_django/plugin.py
- tests/test_database.py
- tests/test_db_access_in_repr.py
- tests/test_environment.py
- tests/test_fixtures.py
pytest fails to handle `pytest.fail.Exception` when raised in `repr`, resulting
in confusing "INTERNALERROR" messages, hiding the real failure (since it
happens during reporting).
This changes pytest-django to raise `RuntimeError` instead.
While this will be fixed via
https://github.com/pytest-dev/pytest/pull/6047 likely, it might be good
to have this anyway (also for older pytest versions).
Fixes https://github.com/pytest-dev/pytest-django/issues/713
Fixes https://github.com/pytest-dev/pytest-django/issues/341
> DB blocker: use RuntimeError instead of pytest.fail

- pytest_django/plugin.py
Pytest-django 3.5.0 attempts to run tests in the same order as Django:
Issue #223, Commit 5a79fba3705376c3f89f5a9e26b8244937d61768
Pytest itself can re-order tests to prioritize previously failed tests
(`--failed-first`), incremental runs of the test suite (`--stepwise`), etc.
However, pytest-django's re-ordering clobbers pytest's, which can break
those options as reported in #819.
By applying the `@pytest.hookimpl(tryfirst=True)` decorator to
`pytest_collection_modifyitems()`, pytest-django's re-ordering happens
first, and does not clobber the later re-ordering performed by pytest.
Fixes #819
> Don't break --failed-first when re-ordering tests

- pytest_django/plugin.py
- tests/test_unittest.py
Ref: https://github.com/pytest-dev/pytest-django/pull/744#issuecomment-600581325
> Remove import of pkg_resources for parsing pytest version

- pytest_django/plugin.py
- tests/test_db_setup.py
Closes https://github.com/pytest-dev/pytest-django/issues/827
`test_django_not_loaded_without_settings` is now failing. That's not a surprise since we import `django` in `plugin.py`. Moving the import in the `pytest_collection_modifyitems` does not work either (since the function is run when collecting tests :upside_down_face: )
I tried looking for eg. a class attribute unique to `TestCase` or `TransactionTestCase` but I didn't find any (not that it would be a great solution :\)
Another solution could be to dynamically import django in `pytest_collection_modifyitems` after checking for `DJANGO_SETTINGS_MODULE`? Please advise if you have other / better ideas :)
I ended up doing the dynamic import, taking inspiration from other places where `django_settings_is_configured` is used. It's a …
> Better order tests when mixing transactional tests and Django test classes

- tox.ini
"extras" gets inherited from "testenv".
> tox: unset extras with non-default factors

- pytest_django/plugin.py
Using `group._addoption` bypasses the check for existing options.
> pytest_addoption: use `group.addoption`

- docs/database.rst
Correcting a minor typo on the https://pytest-django.readthedocs.io/en/latest/database.html page.
> Correct typo in database docs

- .travis.yml
- pytest_django/plugin.py
- tests/test_unittest.py
- tox.ini
Ref: https://github.com/pytest-dev/pytest-django/issues/824
> Work around unittest issue with pytest 5.4.{0,1}

- docs/tutorial.rst
In this sentence:  "You need to tell pytest which Django settings that should be used for test
runs." The word "that" should not be used.
The correct wording should be: "You need to tell pytest which Django settings should be used for test
runs."
> Fix incorrect sentence syntax.

- .travis.yml
- pytest_django/plugin.py
- setup.py
- tests/test_fixtures.py
- tests/test_manage_py_scan.py
- tox.ini
Django 3.1 is due on Monday 2020-08-03 if there isn't another RC release.
https://code.djangoproject.com/wiki/Version3.1Roadmap
This PR also includes two commits with unrelated changes.  They are necessary for the tests to pass.  (They are necessary to let the baseline stage pass on travis and actually run the new job.)
> Run tests against Django 3.1

- pytest_django/fixtures.py
Fixes https://github.com/pytest-dev/pytest-django/issues/860
> support pytest-xdist 2

- pytest_django/compat.py
`time_keeper` is optional since https://github.com/django/django/commit/0b8871ab6744285943784795ede053839ee009ef
This reverts ed04bb0613fb14885efe939d38a7d6ae23a12435.
> Revert workaround for not optional django.test.utils.setup_databases()'s time_keeper.

- .github/workflows/main.yml
- .travis.yml
- pytest_django_test/db_helpers.py
- pytest_django_test/settings_mysql_innodb.py
- pytest_django_test/settings_mysql_myisam.py
- pytest_django_test/settings_postgres.py
- tests/test_db_access_in_repr.py
- tests/test_db_setup.py
- tests/test_django_configurations.py
- tests/test_django_settings_module.py
- tests/test_fixtures.py
- tests/test_initialization.py
- tests/test_unittest.py
- tox.ini
This adds a github actions CI. If it goes well, will remove the travis one.
I tested that the steps work; the coverage and deploy are still untested.
Also fixes #876.
> Switch to github actions

- docs/helpers.rst
I was thinking that I could use the `db` fixture to access a database connection object within a test. However, the `db` fixture returns None. 
This documentation update makes it clear that the `db` fixture does not return an object, and explains that users should use from `django.db import connection` instead.
Reference:
See [this comment](https://github.com/pytest-dev/pytest-django/issues/338#issuecomment-227402089) on issue #338.
> Docs - explain how to get a db connection

- pytest_django/fixtures.py
Using manager's `get_by_natural_key` should be preferred for getting users as oftentimes this method is customized by developers
> admin_user - get user by natural key

- docs/helpers.rst
- pytest_django/fixtures.py
- tests/test_fixtures.py
Fixes #513. Re-spin of #517 with some adjustments.
This bypasses the username+password entirely; they cause complications and may fail.
> Force login admin user in admin_client

- pytest_django/fixtures.py
- pytest_django_test/settings_mysql_innodb.py
- pytest_django_test/settings_mysql_myisam.py
- tests/test_fixtures.py
Replaces PR #843 with some minor updates. Commits by @jnns.
---
Using the `admin_client` fixture with a custom user model that doesn't have a username field doesn't work currently. The fixture assumes that the user model always has a `username` field present. For this case, Django has `User.USERNAME_FIELD` and `User.get_username()`. 
Unfortunately, the existing test didn't catch this issue because a custom user model _with_ `User.username` is used. 
This pull request changes the test setup to use a custom user without `username` and makes `admin_client` use `User.get_username()`.
There are a few merge requests and issues about this problem already. I hope this one meets the requirements to be merged. If not, please let me know and I see what I can do.  
Closes #246
Closes #484
Closes #748 …
> Make admin_user & admin_client fixtures compatible with custom user models

- docs/usage.rst
- pytest_django/plugin.py
- tests/test_django_settings_module.py
> Add django_debug_mode to configure how DEBUG is set in tests

- pytest_django/fixtures.py
- tests/test_database.py
> Disable atomic durability check on non-transactional tests

- docs/helpers.rst
Newcomers get very confused if `request.user` is not set. I think it makes sense to underline this in the example.
> Add `request.user` to example

- docs/database.rst
I shorted the text to be less opinionated.
I disagreed to the previous text: the ORM is a tool like any other tool. If it helps you, then use it. The only reason not to use it, is that
it might slow your tests down.
> Less opinionated wording

- pytest_django/fixtures.py
This lets Django do its thing without us having to implement it
ourselves:
- The durability stuff
- Checking the `databases` attribute (not used yet)
It does some other stuff that relies on attributes that we don't set so
ends up a noop.
> Call Django's setUpClass()/tearDownClass()

- docs/database.rst
- docs/helpers.rst
- pytest_django/fixtures.py
- pytest_django/plugin.py
- pytest_django_test/app/migrations/0001_initial.py
- pytest_django_test/app/models.py
- pytest_django_test/db_helpers.py
- pytest_django_test/db_router.py
- pytest_django_test/settings_base.py
- pytest_django_test/settings_mysql_innodb.py
- pytest_django_test/settings_mysql_myisam.py
- pytest_django_test/settings_postgres.py
- pytest_django_test/settings_sqlite.py
- pytest_django_test/settings_sqlite_file.py
- tests/conftest.py
- tests/test_database.py
- tests/test_db_setup.py
This PR adds experimental support for multi-database configurations - refs #924.
Currently, we only add a `databases` argument to the `django_db` marker, which corresponds to the `databases` attribute of Django's `TransactionTestCase`/`TestCase`. We probably also want some fixture to be able to control this more nicely for an entire file, module, session etc, but that can be done later.
Since I'm not really sure about the API, I marked it as experimental for now. If it works out fine, we can stabilize it.
> Add initial experimental multi database support

- docs/helpers.rst
- pytest_django/fixtures.py
- pytest_django/plugin.py
- tests/test_fixtures.py
Similar to Django's `TestCase.captureOnCommitCallbacks`. Documentation
is cribbed from there.
Fixes #752.
> fixtures: add django_capture_on_commit_callbacks fixture

- docs/contributing.rst
- docs/faq.rst
See https://github.com/pytest-dev/pytest/pull/8722
> doc: Switch to new IRC channel

- docs/database.rst
- docs/managing_python_path.rst
- tests/test_manage_py_scan.py
There are small typos in:
- docs/database.rst
- docs/managing_python_path.rst
- tests/test_manage_py_scan.py
Fixes:
- Should read `implicitly` rather than `impliclity`.
- Should read `implicitly` rather than `implicilty`.
- Should read `explicitly` rather than `explictly`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: Fix a few typos

- pytest_django/asserts.py
Hi! Thank you for this invaluable library.
I recently added a test to my project that looked something like this:
```python
def test_template(client: Client) -> None:
with assertTemplateUsed("app/template.html"):
client.get(URL)
```
This caused a typing error from MyPy:
```
"assertTemplateUsed" does not return a value  [func-returns-value]
```
This is because the [type hints added for this function in `pytest_django/asserts.py`](https://github.com/pytest-dev/pytest-django/blob/cf6b229bce0c717bc590d8fd7cef281f3aa2c1fa/pytest_django/asserts.py#L100-L113) incorrectly indicate a return type of `None`.
I hope this change will fix the error. While I was there, I noticed that the return type of `assertTemplateNotUsed` was similarly incorrect, so I've addressed that too.
I realise that I have …
> assertTemplateUsed return type

- pytest_django_test/settings_base.py
This patch will remove below warning for django main
```
RemovedInDjango50Warning: The default value of USE_TZ will change from False to True in Django 5.0. Set USE_TZ to False in your project settings if you want to keep the current default behavior.
```
> Add USE_TZ to test settings.

- docs/index.rst
using point to sepcify the path to the settings file, instead of underscore
> fix DJANGO_SETTINGS_MODULE  in main documentation

- docs/configuring_django.rst
using point to sepcify the path to the settings file, instead of underscore
> fix  DJANGO_SETTINGS_MODULE docs

- .github/workflows/main.yml
- README.rst
- setup.cfg
- tox.ini
Since Django 3.0 doesn't receive an update, we can also drop it's support.
https://www.djangoproject.com/download/
> Drop Django 3.0 support.

- tests/test_database.py
While taking a look at the project, I saw that there was no test ensuring that mirroring of the database worked as expected when setting `"MIRROR": "default"` option, so I thought it could be nice to add one.
> Add test for mirror database

- AUTHORS
- docs/changelog.rst
- pytest_django/live_server_helper.py
- pytest_django_test/db_helpers.py
- pytest_django_test/settings_sqlite.py
- pytest_django_test/settings_sqlite_file.py
Updates #947 and adds a couple more commits.
> Fix `LiveServer` for in-memory SQLite database on Django >= 3.

- pytest_django/fixtures.py
See https://github.com/pytest-dev/pytest-django/issues/514#issuecomment-982607349
> Skip Django's `setUpTestData` mechanism in pytest-django tests

- tests/test_manage_py_scan.py
https://docs.pytest.org/en/7.0.x/changelog.html#breaking-changes:
> [pytest#8246](https://github.com/pytest-dev/pytest/issues/8246): --version now writes version information to stdout rather than stderr.
Fixes: https://github.com/pytest-dev/pytest-django/issues/995
> tests: Sync expected stream for Pytest' version

- docs/managing_python_path.rst
Expand the documentation to explain how to configure the pythonpath for projects using the src layout.
Fix #738
> docs: configuration for the src layout

- docs/helpers.rst
`response.content` is a `bytes` object and doing a string comparison throws an error
> Fix byte and string comparison

- pytest_django/asserts.py
Changes `assertRaisesMessage` signature definition to be in line with the one defined in the Django stubs.
Fixes #1009
> Fix type in assertRaisesMessage signature

- pytest_django/asserts.py
Updating to the latest version(s) of `django-stubs` from `1.10.1` reveals errors such as:
> Argument 1 to "assertContains" has incompatible type "_MonkeyPatchedWSGIResponse"; expected "HttpResponse"  [arg-type]
`django-stubs` expects a `HttpResponseBase` instead of `HttpResponse` (see: https://github.com/typeddjango/django-stubs/blob/0381fdb0227f0db96a584d8e916ae6d8b3d025a3/django-stubs/test/testcases.pyi#L102)
This PR changes the signatures to be in line with what `django-stubs` defines.
> Fix assert function signatures that expect HTTP response

- .github/workflows/main.yml
- README.rst
- docs/contributing.rst
- setup.cfg
Someone needs to adjust this project's Required Checks to drop the 3.7 requirement :)
> Drop support for Python 3.7 (EOL since June 2023)

- docs/helpers.rst
- pytest_django/fixtures.py
- pytest_django/plugin.py
- tests/test_database.py
Right now in a multi-schema environment, TransactionTestCases may fail to flush if there are foreign key dependencies between schemas because the test case will flush the DB in `_fixture_teardown` (see [source](https://github.com/django/django/blob/24068058a63c506c300629fcc491601abc968926/django/test/testcases.py#L1135-L1143)) but will not cascade truncation by default.
I've encountered this issue in a multi-tenant environment, and another user has posted about a similar issue [here](https://forum.djangoproject.com/t/transactiontestcase-available-apps-allow-cascade-true-db-cannot-be-flushed/18111).
Setting `available_apps` will enable `CASCADE` during truncation per the django docs ([link](https://docs.djangoproject.com/en/4.1/topics/testing/advanced/#django.test.TransactionTestCase.availa …
> Expose available_apps in django_db marker

- pytest_django/live_server_helper.py
This moves activation of `LiveServer.thread` to a method. My primary motivation here is to delay thread activation so I can change the parameters of the thread in an overriden `live_server` fixture. This provides a work-around to issue #294 using the following override:
```python
import os
import pytest
from django.test.testcases import _StaticFilesHandler
from pytest_django import live_server_helper
from pytest_django.lazy_django import skip_if_no_django
@pytest.fixture(scope="session")
def live_server(request):
skip_if_no_django()
addr = (
request.config.getvalue("liveserver")
or os.getenv("DJANGO_LIVE_TEST_SERVER_ADDRESS")
or "localhost"
)
server = live_server_helper.LiveServer(addr)
server.thread.static_handler = _StaticFilesHandler  # Force _StaticFilesHandler
server.start() …
```
> Move thread activation to start method

- pytest_django/plugin.py
- tests/test_environment.py
after a test using ignore_template_errors marker.
Otherwise, the first test set `fail` to `False`, never to be changed again.
> Make sure InvalidVarException.fail is reset

- README.rst
- pytest_django/asserts.py
- pytest_django/fixtures.py
- pytest_django/plugin.py
- setup.cfg
- tests/conftest.py
- tests/helpers.py
- tests/test_database.py
- tests/test_db_access_in_repr.py
- tests/test_db_setup.py
- tests/test_django_configurations.py
- tests/test_django_settings_module.py
- tests/test_environment.py
- tests/test_fixtures.py
- tests/test_initialization.py
- tests/test_manage_py_scan.py
- tests/test_unittest.py
- tests/test_urls.py
- tests/test_without_django_loaded.py
- tox.ini
Change from testdir -> pytester, type annotate pytest stuff.
> Require pytest>=7.0

- pytest_django/plugin.py
- tests/test_django_configurations.py
- tests/test_django_settings_module.py
Fix #987.
Before:
```
platform linux -- Python 3.11.4, pytest-7.4.2, pluggy-1.3.0
django: settings: conf.settings (from ini)
rootdir: /my/project
configfile: pytest.ini
plugins: xdist-3.3.1, snapshot-0.9.0, django-4.5.3.dev49+g055f251
```
After:
```
platform linux -- Python 3.11.4, pytest-7.4.2, pluggy-1.3.0
django: version: 4.2.5, settings: conf.settings (from ini)
rootdir: /my/project
configfile: pytest.ini
plugins: xdist-3.3.1, snapshot-0.9.0, django-4.5.3.dev49+g055f251
```
> Show Django's version in the django report header

- pyproject.toml
- pytest_django/plugin.py
- tests/test_unittest.py
Django TestCase supports tags:
https://docs.djangoproject.com/en/4.2/topics/testing/tools/#topics-tagging-tests These are basically similar to (basic) Pytest tags, so let's interpret them to allow using the native pytest-native markers functionality. This helps projects which are unable to convert tags to markers.
This may cause breakage for projects using `strict-markers`. Such projects would need to add the tags to their `markers` config, or deal with it some other way.
Fix #818.
> Convert Django test tags to Pytest markers

- .github/workflows/main.yml
- README.rst
- docs/changelog.rst
- pyproject.toml
- tox.ini
Copied the changes from #1044 for this new Django version.
> Add Django 5.0 support

- .github/workflows/main.yml
- docs/changelog.rst
- pyproject.toml
- tox.ini
Without any changes this project supports Python 3.12. So version 4.6.0 is already compatible with Python 3.12
> Add Python 3.12 support

- .readthedocs.yml
Try to fix this error:
> Problem in your project's configuration. Invalid configuration option
> "build.os": build not found
> Maybe fix readthedocs build failures

- docs/Makefile
This has been the default [since Sphinx 1.5](https://www.sphinx-doc.org/en/master/changes.html#release-1-5-released-dec-5-2016): “Use make-mode of sphinx-quickstart by default. To disable this, use -M option”
> Move docs to use Sphinx's minimal Makefile

- docs/helpers.rst
- pytest_django/__init__.py
- pytest_django/fixtures.py
- tests/test_fixtures.py
For users (like me) who like to type annotate their tests, this adds types in `pytest_django` for typing the `django_capture_on_commit_callbacks`, `django_assert_num_queries` and `django_assert_max_num_queries` fixtures (in addition to `django_db_blocker` from a previous PR).
> Some more typing support for pytest-django fixtures

- docs/contributing.rst
- pyproject.toml
- tests/conftest.py
- tests/test_urls.py
- tox.ini
This makes just `pytest` run successfully.
>  tests: make it possible to run without setting `PYTHONPATH=$(pwd)`

- pytest_django/plugin.py
- tests/test_manage_py_scan.py
>  Fix --help/--version crash in a partially configured app 

- AUTHORS
- docs/changelog.rst
- pytest_django/asserts.py
- tests/test_asserts.py
Hi, let me know if you'd like this implemented differently and I can amend. This is my first time contributing to pytest-django.
Thanks!
> Added assertMessages() from django.contrib.messages.

- docs/helpers.rst
so that the password is hashed and `client.login` etc. works as expected
> django_username_field example should use create_user not create

- docs/changelog.rst
Just saw a little typo in the changelog I added, and added an intersphinx link. Great to see the quick release!
> Fixed changelog.rst typo and added link to Django documentation.

- docs/changelog.rst
> Mention django 2.2 support drop in changelog

- pytest_django/plugin.py
- tests/test_environment.py
When using the `@pytest.mark.ignore_template_errors` on a test, we could expect the test to return to its original behavior (just like running them without `--fail-on-template-vars`).
This would ease the use of the option since ignored tests are less likely to crash.
> fail-on-template-vars: be more discreet with ignore_template_errors

- pytest_django/fixtures.py
- pytest_django/plugin.py
This PR adds short docstrings to quickly check available fixtures and is especially usefull for new pytest-django users.
I've noticed that some public fixtures don't have docstrings to give the ability to quickly check what this fixture does.
For example, the command `pytest --fixtures`  shows builtin and custom fixtures with their short descriptions, but pytest-django doesn't provide them all:
```
...
-------------------------------------------------------------- fixtures defined from pytest_django.plugin --------------------------------------------------------------- 
django_test_environment [session scope] -- pytest_django\plugin.py:479
Setup Django's test environment for the testing session.
django_db_blocker [session scope] -- pytest_django\plugin.py:507
Wrapper around Django's …
```
> Add docstrings to public fixtures

- .github/workflows/deploy.yml
- .github/workflows/main.yml
See https://docs.pypi.org/trusted-publishers/. Loosely based on pytest CI.
> ci: use trusted publishing for release

- pytest_django/plugin.py
- tests/test_db_setup.py
> Avoid running database migrations for `SimpleTestCase`

- pytest_django/plugin.py
inspect.stack() returns a list of namedtuple (or retrocompatible objects) since Python 3.5+: let's use the named attribute.
cf https://docs.python.org/3/library/inspect.html#inspect.stack
And once we have access to a FrameInfo object/namedtuple, access to its frame object and its f_locals member should not need to iterate on all its members:
https://docs.python.org/3/reference/datamodel.html#frame-objects
> fail-on-template-vars: modernize stack inspection code

- pytest_django/fixtures.py
- pytest_django/plugin.py
As the code is written currently, it's possible the `restore` is not called in case of exception. Use the context manager to ensure that it does.
This is not to fix an observed issue, just a fix from reviewing the code.
Also took the chance to update the `django_db_blocker` docstring a bit.
> fixtures: ensure db blocker is always restored

- Makefile
- pytest_django/plugin.py
`restore` pops the `block` in `_setup_django`, while `unblock` pushes an unblock. We want to leave things clean, so should `restore`.
> plugin: unconfigure should `restore` not `unblock`

- .github/workflows/main.yml
As mentioned in the title, [django does not support py11 in the latest (main) branch](https://github.com/django/django/blob/main/pyproject.toml#L8) and its causing that particular test to fail.
Let me know if you want me to move things around.
_This came about because i wanted to do https://github.com/pytest-dev/pytest-django/pull/1170 and ran into this issue there._
> Fixes CI issue with main + py11

- .github/workflows/main.yml
- tox.ini
* This update addresses two common pain points when developing on GitHub.com's browser editor:
1. Delayed CI Testing: Small changes often accumulate, causing the CI to wait for all previous commits before testing your current commit. This delay can be inefficient. Suggestion: Cancel previous CI runs when pushing new commits to speed up the feedback loop.
2. Lack of Fix Suggestions for `ruff` Issues: When ruff flags an issue, it highlights the problematic code block but doesn't suggest how to fix it. By adding the `--diff` option, you can see the differences and get guidance on correcting the issue.
All this came about while working on https://github.com/pytest-dev/pytest-django/pull/1170
> Developer QOL

- .github/workflows/main.yml
- docs/changelog.rst
- docs/helpers.rst
- pytest_django/fixtures.py
- tests/test_fixtures.py
* Depend on https://github.com/pytest-dev/pytest-django/pull/1171
Adds quality of life to replace
```python
from django.db import connections
def test_test():
with django_assert_num_queries(1, connection=connections["log"]):
Model.objects.get()
```
with
```python
def test_test():
with django_assert_num_queries(1, using="log"):
Model.objects.get()
```
_I have multiple DBs and this is driving me nuts..._
> Adds using to assert_num_queries

- .github/workflows/main.yml
- README.rst
- docs/changelog.rst
- pyproject.toml
- tox.ini
It’s in beta since Feb 19: https://www.djangoproject.com/weblog/2025/feb/19/django-52-beta-1-released/ . Final release expected April 2nd.
Since we're already testing the main branch, few changes are needed.
I copied what to change from #1143.
I’m a bit confused about what entries we include on the testing matrix, so I just added a few that I thought would make sense.
> Add support for Django 5.2

- docs/faq.rst
- pytest_django/runner.py
- tests/conftest.py
- tests/test_environment.py
- tests/test_runner.py
To lower the barier of entry for questions like https://github.com/pytest-dev/pytest-django/issues/1169
> Integrate pytest into django's manage.py test

- docs/changelog.rst
- pytest_django/fixtures.py
> Only setup and serialize databases as needed by tests

- docs/changelog.rst
- pytest_django/fixtures.py
- tests/test_database.py
Accidentally used the wrong variable.
Fixes #1188.
> fixtures: fixup a regression in previous release for TestCase multi-db support

- pytest_django/asserts.py
This will help with editor autocomplete and so it gets recognised as a valid import.
> Add type definition for assertNotInHTML

- .github/zizmor.yml
- pyproject.toml
- tox.ini
TODO: change `--persona=regular` -> `--persona=pedantic` (in another PR)
> Add github actions static analysis

- .github/workflows/main.yml
- tox.ini
Continuation of: https://github.com/pytest-dev/pytest-django/pull/1211
> Pedantic static analisis for github actions

- .github/workflows/main.yml
Fixes issue where multiple PRs trying to merge into main are being blocked. When working on multiple PRs at a time.. this is a real pain point!
> Fix CI concurrency

- .github/workflows/main.yml
For the most part, the "Install dependencies" step, sees a decrease of 2-3s for each job
[Main](https://github.com/pytest-dev/pytest-django/actions/runs/15476151028)
[This PR](https://github.com/pytest-dev/pytest-django/actions/runs/15478405158?pr=1216)
> Adds uv to tox

- tests/test_fixtures.py
There are weird tests in `TestLiveServer.test_settings_before`/`test_settings_restored` that requires `xdist` to not be used. Since they set a global variable, and due to how xdist works, you cannot guarantee the order or the same worker.
I'm in two minds about this... My gut tells me to remove this test.. but I want to first get your opinion.
> Skip test that cannot be ran in parallel
